spring:
  r2dbc:
    # r2dbc的数据库配置文件
    username: root
    password: LingXi666
    url: r2dbc:mysql://linshio.cn:3306/test
    name: test
  main:
    allow-circular-references: true

logging:
  level:
    org.springframework.r2dbc: debug